{{ if (.Values.service.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name.secondservice }}
  labels:
    app: {{ .Values.service.name.secondservice }}-{{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Values.service.name.secondservice }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.secondservice }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.service.name.secondservice }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ if (.Values.service.expose) }}
---
#nginx#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.service.name.secondservice }}
  labels:
    app: {{ .Values.service.name.secondservice }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.service.name.secondservice }}.{{ .Release.Namespace }}.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.service.name.secondservice }}
              servicePort:  {{ .Values.service.port.secondservice }} 
#nginxEnd#
---
{{- end -}}
{{- end -}}